---
name: Deploy
on:
  push:
    branches:
      - main
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
jobs:
  deploy:
    runs-on: windows-latest
steps:
  - name: Checkout code
    uses: actions/checkout@v2
  - name: Setup .NET Core
    uses: actions/setup-dotnet@v1
    with:
      dotnet-version: 6.0.x
  - name: Install MSBuild
    uses: microsoft/setup-msbuild@v1
    with:
      msbuild-version: 16.9
  - name: Build project
    run: dotnet build SkEditorPlus/SkEditorPlus/SkEditorPlus.csproj
  - name: Publish project
    run: dotnet publish SkEditorPlus/SkEditorPlus/SkEditorPlus.csproj -c Release -r
      win10-x64
  - name: Upload artifact
    uses: actions/upload-artifact@v2
    with:
      name: SkEditorPlus
      path: SkEditorPlus/SkEditorPlus/bin/Release/net6.0/win10-x64/publish
